version: '2'
services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    build: .
    ports:
      # Keep external port in sync with KAFKA_ADVERTISED_PORT
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1 # TODO add a test to verify this is up to date
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1 # specify if you want persistence across restarts
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: unless-stopped
