name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lines:
    name: Less than 500 lines
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install SLOCCount
      run: go install github.com/hhatto/gocloc/cmd/gocloc@latest

    - name: Check <500 lines
      run: |
        loc=$(${HOME}/go/bin/gocloc --not-match=test.go --not-match-d="app|bench|client|test" . | grep -oP '^Go.*([0-9]+)$' | awk '{print $5}')
        echo "Go LOC: ${loc}"
        if [ $loc -gt 500 ];
          then exit 1;
        fi
      shell: bash

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v . ./client

    - name: Test
      run: go test -v --count=100 . ./client

    - name: Test for data race
      run: go test -v -race --count=100 . ./client

    - name: Test in Containers
      run: cd test && docker-compose up --abort-on-container-exit

    - name: Benchmark minikafka
      run: go test -v ./bench/minikafka
