name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lines:
    name: Less than 500 lines
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}

    - name: Install SLOCCount
      run: go install github.com/hhatto/gocloc/cmd/gocloc@latest

    - name: Check <500 lines
      run: $GOROOT/bin/gocloc .
      shell: bash

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install dependencies
      run: sudo apt-get install -y libczmq-dev pkg-config

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
